unique_name: Product Dimension
object_type: dimension
label: Product Dimension
type: standard
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    levels:
      - unique_name: Category
        level_attributes:
          - unique_name: Category
            label: Category
            dataset: ds_category
            name_column: dept_name
            key_columns:
              - id
      - unique_name: Product Name
        level_attributes:
          - unique_name: Product Name
            label: Product Name
            is_unique_key: true
            dataset: ds_product
            name_column: name
            key_columns:
              - id
        secondary_attributes:
          - unique_name: d_brand
            label: Brand
            dataset: ds_product
            name_column: brand
            key_columns:
              - brand
          - unique_name: d_list_price
            label: List Price
            dataset: ds_product
            name_column: price
            key_columns:
              - price
relationships:
  - unique_name: Product_Category
    from:
      hierarchy: Product Hierarchy
      level: Product Name
      dataset: ds_product
      join_columns:
        - dept
    to:
      dimension: Product Dimension
      level: Category
    type: embedded
